### ISSUE TITLE
UPC-E support

### ISSUE THREAD

**Issue by bilotilvv** [hitmeister/gtin-validator#6]
I want to use this library. I need UPC-E. 
UPC-E is a 0-Suppressed UPC (GTIN-12).

Would you like to add support for it?
I can prepare a pull request, to help you.

**Comment by radarlog** [comment]
Hey,

Seems there is already a feature for that. Please take a look onto the [corresponding](https://github.com/real-digital/gtin-validator/blob/master/tests/Gtin/Gtin12Test.php#L106) test.

Does this work for you?

**Comment by bilotilvv** [comment]
@radarlog , thanks for a quick answer. I see what you meant. However, in term of UPC-E zero-suppression works in a different way. Here is a [good article](http://www.barcodeisland.com/upce.phtml) that explains how zeros in the middle of UPC can be removed to create UPC-E. 
UPC-E contains 8 digits. The first digit has to be "zero" (https://www.gtin.info/upc/). The last digit is a checksum of UPC. Only some UPC can be converted to UPC-E.

In my view, method `Upce::padded()` should return "GTIN-12" padded to "GTIN-14". And `Upce::key()` should return 8 digits as "UPC-E" is.

**Comment by radarlog** [comment]
@bilotilvv thanks for the links.

I'm not sure `UPC-E` should implement `Gtin` interface. Probably a separate converter should be implemented, that receives a `Gtin12` instance and tries to convert it to `UPC-E` format:

```php
<?php
declare(strict_types=1);

namespace Real\Validator\Gtin;

final class Upce
{
    /** @var Gtin12 */
    private $gtin;

    public function __construct(Gtin12 $gtin)
    {
        $this->gtin = $gtin;
    }
}
```

What do you think?

**Comment by bilotilvv** [comment]
@radarlog , thank you. I close issue. I do not need this feature any more.
